core/urls.py
from django.contrib import admin
from django.urls import path, include 

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student_info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_info/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('add_student/', views.add_student, name='add_student'),
    path('all_student/', views.all_student, name='all_student'),
    path('content/', views.content, name='content'),
    path('detele_student/<int:std_id>/', views.detele_student, name='detele_student'),
    path('edit_student/<int:std_id>/', views.edit_student, name='edit_student'),
    path('view_student/<int:std_id>/', views.view_student, name='view_student'),
]

student_info/models.py
from django.db import models


class Student(models.Model):

    # ---------- GENDER CHOICES ----------
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    # ---------- COUNTRY CHOICES ----------
    COUNTRY_CHOICES = [
        ('usa', 'USA'),
        ('australia', 'Australia'),
        ('canada', 'Canada'),
    ]

    # ---------- BASIC INFO ----------
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    tel = models.CharField(max_length=15)
    dob = models.DateField()

    # ---------- CHOICES FIELD ----------
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    country = models.CharField(max_length=20, choices=COUNTRY_CHOICES)

    # ---------- IMAGE ----------
    profile_pic = models.ImageField(upload_to='students/', null=True, blank=True)

    # ---------- MESSAGE ----------
    message = models.TextField(max_length=300)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

student_info/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Student
from django.http import HttpResponse


def home(request):
    return render(request, 'student_info/index.html')


def add_student(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        tel = request.POST.get('tel')
        dob = request.POST.get('dob')
        gender = request.POST.get('gender')
        country = request.POST.get('country')
        message = request.POST.get('message')
        image = request.FILES.get('profile_pic')

        Student.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            tel=tel,
            dob=dob,
            gender=gender,
            profile_pic=image,
            country=country,
            message=message,
        )

        return redirect('all_student')

    return render(request, 'student_info/add_student.html')


def all_student(request):
    student_data = Student.objects.all()
    context = {'data': student_data}
    return render(request, 'student_info/all_student.html', context)


def content(request):
    return render(request, 'student_info/content.html')


def detele_student(request, std_id):

    # student = Student.objects.filter(id=std_id)
    # student.delete()

    student = get_object_or_404(Student, id=std_id)

    student.delete()

    return redirect('all_student')



def edit_student(request, std_id):

    student_data = get_object_or_404(Student, id=std_id)

    if request.method == "POST":
        student_data.first_name = request.POST.get('first_name')
        student_data.last_name = request.POST.get('last_name')
        student_data.email = request.POST.get('email')
        student_data.tel = request.POST.get('tel')
        student_data.dob = request.POST.get('dob')
        student_data.gender = request.POST.get('gender')

        if request.FILES.get('profile_pic'):
            if student_data.profile_pic:
                student_data.profile_pic.delete(save=False)
            student_data.profile_pic = request.FILES.get('profile_pic')


        student_data.country = request.POST.get('country')
        student_data.message = request.POST.get('message')

        student_data.save()
        return redirect('all_student')



    context = {
        'student' : student_data
    }

    return render(request, 'student_info/edit_student.html', context)


def view_student(request, std_id):
    student_data = get_object_or_404(Student, id=std_id)
    context = {'student': student_data}
    return render(request, 'student_info/view_student.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

        {% block title %}

        {% endblock %}

    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% include 'includes/header.html' %}

    {% block content %}

    {% endblock %}

    {% include 'includes/footer.html' %}

</body>
</html>

templates/includes/footer.html
<footer>
    &copy; 2026 All rights reserved by 101.
</footer>

templates/includes/header.html
<ul>
  <li><a href="{% url 'home' %}">Home</a></li>
  <li><a href="{% url 'add_student' %}">Add Student</a></li>
  <li><a href="{% url 'all_student' %}">All Student</a></li>
  <li><a href="{% url 'content' %}">Contact</a></li>
</ul>

templates/student_info/add_student.html
{% extends 'base.html' %}



{% block title %}
    Add_Student Page
{% endblock %}



{% block content %}

<h2>Add Add_Student</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="fname">First Name</label>
  <input type="text" id="fname" name="first_name" placeholder="Your First Name..">

  <label for="lname">Last Name</label>
  <input type="text" id="lname" name="last_name" placeholder="Your last Name..">

  <label for="lname">Email</label>
  <input type="email" id="email" name="email" placeholder="Your email">

  <label for="lname">Phone Number</label>
  <input type="tel" id="tel" name="tel" placeholder="Your Content Number">

  <label for="lname">Date of Birth</label>
  <input type="date" id="dob" name="dob">

  <br>
  <br>

  <label for="lname">Gender</label>
  <br>
  <input type="radio" id="male" name="gender" value="male"> Male
  <input type="radio" id="female" name="gender" value="female"> Female

  <br>
  <br>
  <br>


  <label for="image">Upload Your Picture</label>
  <input type="file" id="image" name="profile_pic">

  <label for="country">Country</label>
  <select id="country" name="country">
    <option value="australia">Australia</option>
    <option value="canada">Canada</option>
    <option value="usa">USA</option>
  </select>


  <label for="lname">Your Message</label>
  <textarea name="message" id="" placeholder="Your Writhe See Something"></textarea>
  
  <input type="submit" value="Submit">
</form>


{% endblock %}

templates/student_info/all_student.html
{% extends 'base.html' %}



{% block title %}
    All_Student Page
{% endblock %}



{% block content %}

<section class="all_student">

    <h1>Student Information Table</h1>

<table>
  <tr>
    <th>Full Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Date of Birth</th>
    <th>Gender</th>
    <th>Country</th>
    <th>Upload Your Picture</th>
    <th>Your Message</th>
    <th>Action</th>
  </tr>
  
  {% for student in data %}

  <tr>

    <td> {{ student.first_name }} {{ student.last_name }} </td>
    <td> {{ student.email }} </td>
    <td> {{ student.tel }} </td>
    <td> {{ student.dob }} </td>
    <td> {{ student.gender | title }} </td>
       <td>

    {% if student.country == 'usa' %}
    {{ student.country | upper }}
    {% else %}
    {{ student.country | title }}
    {% endif %}

    </td>

    <td>
       {% if student.profile_pic %}

       <img src="{{ student.profile_pic.url }}" alt="Profile_pic" width="80px">
        {% else %}
        <p>No image found!!</p>
        {% endif %}

    </td>
    <td>{{ student.message }}</td>

    <td>
      <a href="{% url 'view_student' student.id %}">View</a>  
      <a href="{% url 'edit_student' student.id %}">Eidit</a>
        <a href="{% url 'detele_student' student.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}

</table>

</section>

{% endblock %}

templates/student_info/content.html
{% extends 'base.html' %}



{% block title %}
    Content Page
{% endblock %}



{% block content %}
    <h2>Welcome to Content Page Page !!!!</h2>
{% endblock %}

templates/student_info/edit_student.html
{% extends 'base.html' %}



{% block title %}
    Edit Student Page
{% endblock %}



{% block content %}

<h2>Edit Student Information</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="fname">First Name</label>
  <input type="text" id="fname" name="first_name" value="{{ student.first_name }}" placeholder="Your First Name..">

  <label for="lname">Last Name</label>
  <input type="text" id="lname" name="last_name" value="{{ student.last_name }}" placeholder="Your last Name..">

  <label for="lname">Email</label>
  <input type="email" id="email" name="email" value="{{ student.email }}" placeholder="Your email">

  <label for="lname">Phone Number</label>
  <input type="tel" id="tel" name="tel" value="{{ student.tel }}" placeholder="Your Content Number">

  <label for="lname">Date of Birth</label>
  <input type="date" id="dob" name="dob" value="{{ student.dob|date:'Y-m-d' }}">

  <br>
  <br>

  <label for="lname">Gender</label>
  <br>
  <input type="radio" id="male" name="gender" value="male" 
  {% if student.gender == 'male' %}
  checked
  {% endif %}
  > Male
  <input type="radio" id="female" name="gender" value="female" 
  {% if student.gender == 'female' %}
  checked
  {% endif %}
  > Female

  <br>
  <br>
  <br>


    <label for="old_img">Old Images</label>

    {% if student.profile_pic %}
        <img src="{{student.profile_pic.url }}" alt="" width="100">
        {% endif %}

  <label for="image">Upload Your Picture</label>
  <input type="file" id="image" name="profile_pic">

  <label for="country">Country</label>
 <select name="country">
    <option value="australia" {% if student.country == "australia" %}selected{% endif %}>Australia</option>

    <option value="canada" {% if student.country == "canada" %}selected{% endif %}>Canada</option>

    <option value="usa" {% if student.country == "usa" %}selected{% endif %}>USA</option>
</select>
  </select>


  <label for="lname">Your Message</label>
  <textarea name="message" id="" placeholder="Your Writhe See Something">{{student.message}}</textarea>
  
  <input type="submit" value="Submit">
</form>


{% endblock %}

templates/student_info/index.html
{% extends 'base.html' %}



{% block title %}
    Home Page
{% endblock %}



{% block content %}
    <h2>Welcome to Home Page !!!!</h2>
{% endblock %}

templates/student_info/view_student.html
{% extends 'base.html' %} {% load static %}

<title>
  {% block title %} Profile - {{ student.first_name }} {{ student.last_name }}
  {% endblock %}
</title>

{% block content %}

<div class="profile-container">
  <div class="profile-card">
    <div class="profile-image">
      {% if student.profile_pic %}
      <img src="{{ student.profile_pic.url }}" alt="Avatar" />
      {% endif %}
    </div>

    <div class="profile-info">
      <h2>{{ student.first_name }} {{ student.last_name }}</h2>
      <h5 class="email">{{ student.email }}</h5>
      <h5 class="tel">{{ student.tel }}</h5>
      <h5 class="dob">{{ student.dob }}</h5>
      <h5 class="gender">{{ student.get_gender_display }}</h5>
      <h5 class="country">{{ student.get_country_display }}</h5>
      <h5 class="message">{{ student.message }}</h5>
      <a class="edit-btn" href="{% url 'edit_student' student.id %}">
        Edit Profile
      </a>
    </div>
  </div>
</div>

{% endblock %}